import { Inter, Exo_2 } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const exo2 = Exo_2({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={exo2.className}>{children}</body>
    </html>
  );
}
