import { Inter, Exo_2 } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";


const inter = Inter({ subsets: ["latin"] });
const exo2 = Exo_2({ subsets: ["latin"] });

export const metadata = {
  title: "Sam Strike",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="bg-backgroundImage bg-[#0f172a]  bg-blend-overlay bg-no-repeat overflow-x-hidden">
      <body className={`${exo2.className}  overflow-x-hidden`}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
